version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - node-network

  backend:
    build: ./backend
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017/challenge
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    networks:
      - node-network

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - node-network

volumes:
  mongodb_data:

networks:
  node-network:
    driver: bridge
